[project]
name = "ebay-tracker"
version = "0.1.0"
description = "A script that tracks eBay item prices over time"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4==4.12.2",
    "numpy==1.26.2",
    "playwright==1.49.1",
]
